sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
matrix:
  # pypy3 (as of 2.4.0) has a wacky arity issue in its source loader. Allow it
  # to fail until we can test on, and require, PyPy3.3+. See invoke#358.
  allow_failures:
    - python: pypy3
  # Disabled per https://github.com/travis-ci/travis-ci/issues/1696
  # fast_finish: true
before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry
install:
  - poetry install
before_script:
  # Fast syntax check failures for more rapid feedback to submitters
  # (Travis-oriented metatask that version checks Python, installs, runs.)
  - inv travis.blacken
  - flake8
script:
  # Run tests w/ coverage first, so it uses the local-installed copy.
  # (If we do this after the below installation tests, coverage will think
  # nothing got covered!)
  - inv coverage --report=xml
  # TODO: tighten up these install test tasks so they can be one-shotted
  - inv travis.test-installation --package=invocations --sanity="inv --list"
  - inv travis.test-packaging --package=invocations --sanity="inv --list"
  - inv docs --nitpick
# TODO: after_success -> codecov, once coverage sucks less XD
notifications:
  irc:
    channels: "irc.freenode.org#invoke"
    template:
      - "%{repository_name}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: false
